#SPDX-License-Identifier: MIT-0
---
# vars file for rhel-tools-role
# Download URLs

# NOTE: GitHub release URLs with JWT tokens expire. Get fresh URLs from:
# Podman: https://github.com/containers/podman/releases (look for podman-remote-static-linux_amd64.tar.gz)
podman_download_url: "https://github.com/containers/podman/releases/download/v5.3.1/podman-remote-static-linux_amd64.tar.gz"
skopeo_download_url: "https://github.com/containers/skopeo/archive/refs/tags/v1.17.0.tar.gz"
httpd_download_url: "https://dlcdn.apache.org/httpd/httpd-2.4.65.tar.gz"

# AlmaLinux repository base URLs for dynamic package lookup
almalinux_baseos_repo_url: "https://repo.almalinux.org/almalinux/10.0/BaseOS/x86_64/os/Packages/"
almalinux_appstream_repo_url: "https://repo.almalinux.org/almalinux/10.0/AppStream/x86_64/os/Packages/"

git_download_url: "https://www.kernel.org/pub/software/scm/git/git-2.9.5.tar.gz"
wget_download_url: "https://ftp.gnu.org/gnu/wget/wget-1.25.0.tar.gz"
curl_download_url: "https://curl.se/download/curl-8.17.0.tar.gz"
vim_download_url: "https://anduin.linuxfromscratch.org/LFS/vim-9.0.1677.tar.gz"
telnet_download_url: "https://ftp.gnu.org/gnu/inetutils/inetutils-1.9.4.tar.xz"
jq_download_url: "https://github.com/stedolan/jq/releases/download/jq-1.7/jq-linux64"
buildah_download_url: "https://github.com/containers/buildah/archive/refs/tags/v1.41.0.tar.gz"
openssl_download_url: "https://www.openssl.org/source/openssl-3.4.0.tar.gz"
helm_download_url: "https://get.helm.sh/helm-v3.16.3-linux-amd64.tar.gz"
haproxy_download_url: "https://www.haproxy.org/download/3.1/src/haproxy-3.1.0.tar.gz"
rsync_download_url: "https://download.samba.org/pub/rsync/src/rsync-3.4.1.tar.gz"

# Project directories
project_root: "{{ playbook_dir | dirname }}"
build_dir: "{{ project_root }}/build"

# Local directories (on control node)
local_download_dir: "{{ build_dir }}/tools_download"
local_extract_dir: "{{ build_dir }}/tools_extract"
local_combined_tar: "{{ build_dir }}/tools_download.tar.gz"

# Remote paths (on target nodes)
remote_tar_file: "/tmp/tools_download.tar.gz"
remote_install_temp: "/tmp/tools_extracted"
install_dir: "/usr/local/bin"
httpd_install_dir: "/opt/httpd"

# List of binaries to verify
binaries_to_check:
- podman
- skopeo
- httpd
- htpasswd
- firewalld
- dnsmasq
- git
- wget
- curl
- vim
- dig
- nslookup
- telnet
- jq
- buildah
- openssl
- helm
- haproxy
- rsync
